version: '2'
services:
    samba:
        build: ./samba
        image: mynas-smb
        hostname: mynas-smb
        command: ['-u user;1234;200', '-s public;/media;yes;no;no;all;user']
        ports:
            - "137:137/udp"
            - "138:138/udp"
            - "139:139"
            - "445:445"
        volumes:
            - media:/media
    dlna:
        build: ./dlna
        image: mynas-dlna
        hostname: mynas-dlna
        ports:
            - "1900:1900/udp"
            - "8200:8200"
        volumes:
            - media:/media
        network_mode: "host"
volumes:
  media:
